version: "3.2"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - ./data:/data
  signals-commands:
    volumes:
        - ./signal_publisher/:/mnt/
    build: ./signal_publisher
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on:
      - redis
  signals-queries:
    volumes:
        - ./signal_processor/:/mnt/
    build: ./signal_processor
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on:
      - redis    

  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - signals-queries
        - signals-commands
